bon_plan:
    resource: "@BonPlanBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
bonPlan_api:
    resource: "@BonPlanBundle/Resources/config/routing.yml"
    prefix:   /api
