<?php

namespace BonPlanBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getnomcat ($id){
        $query=$this->getEntityManager()->createQuery(
            "select c.nomCategorie from BonPlanBundle:Categorie c where  c.id=:id")

            ->setParameter('id',$id);
        return $query->getResult();
    }



}
