<?php

namespace BonPlanBundle\Repository;

/**
 * promotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class promotionRepository extends \Doctrine\ORM\EntityRepository
{

    public function findDescription($description,$user)
    {
        $q=$this->createQueryBuilder('p')
            ->andWhere('p.description LIKE :description')
            ->andWhere('p.userPlan= :user')

            ->setParameter(':user',$user)

            ->setParameter(':description',"%$description%");
        return $q->getQuery()->getResult();
    }
    public function findDescriptionAdmin($description)
    {
        $q=$this->createQueryBuilder('p')
            ->andWhere('p.description LIKE :description')



            ->setParameter(':description',"%$description%");
        return $q->getQuery()->getResult();
    }
    public function findByuser($user){
        $query=$this->createQueryBuilder('c')
            ->where('c.userPlan= :user')

            ->setParameter(':user',$user);

        return $query->getQuery()->getResult();
    }
}
