<?php

namespace BonPlanBundle\Repository;
use BonPlanBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
function findRecByPlan($userPlan){

    $query=$this->getEntityManager()
        ->createQuery("select r from BonPlanBundle:Reclamation r 
                             WHERE r.userPlan = :plan ")
        ->setParameter('plan',$userPlan);

    return $query->getResult();
}

<<<<<<< HEAD
    function findRecByUs($userVisiteur){

        $query=$this->getEntityManager()
            ->createQuery("select r from BonPlanBundle:Reclamation r 
                             WHERE r.userVisiteur = :visiteur ")
            ->setParameter('visiteur',$userVisiteur);

        return $query->getResult();
    }
=======

>>>>>>> 1c4d0f271342a3deebb8766ad8e9dbb8d20e4b6e
}
