<?php

namespace BonPlanBundle\Repository;
use BonPlanBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProp($nomPlan)
    {
        $q=$this->createQueryBuilder('p')
            ->where('p.nomPlan LIKE :nomPlan')
            ->setParameter(':nomPlan',"%$nomPlan%");
        return $q->getQuery()->getResult();
    }
    public function findRole($role)
    {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from($this->User, 'u')
            ->where('u.roles LIKE "ROLE_PROP"')
            ->setParameter('roles', '%"'.$role.'"%');

        return $qb->getQuery()->getResult();
    }
    public function findCategorie($role,$categorie)
    {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from($this->User, 'u')
            ->where('u.roles LIKE "ROLE_PROP"')
            ->andWhere('u.categorie LIKE :categorie')
            ->setParameter('roles', '%"'.$role.'"%')
        ->setParameter(':categorie',"%$categorie%");

        return $qb->getQuery()->getResult();
    }

}
