Promotion:
    type: entity
    table: promotion
    indexes:
        fk_promotion_fos_user1_idx:
            columns:
                - fos_user_id
    id:
        idpromotion:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idPromotion
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        urlpromo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: urlPromo
        datedebutp:
            type: date
            nullable: false
            column: dateDebutP
        datefinp:
            type: date
            nullable: false
            column: dateFinP
    manyToOne:
        fosUser:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fos_user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
