Reclamation:
    type: entity
    table: reclamation
    indexes:
        fk_reclamation_fos_user1_idx:
            columns:
                - fos_user_id
        fk_reclamation_fos_user2_idx:
            columns:
                - fos_user_id1
    id:
        idreclamation:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idReclamation
            generator:
                strategy: IDENTITY
    fields:
        etat:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        type:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        nivRec:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: niv_rec
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        fosUser:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fos_user_id:
                    referencedColumnName: id
            orphanRemoval: false
        fosUser1:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fos_user_id1:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
