bon_plan_homepage:
    path:     /
    defaults: { _controller: BonPlanBundle:Default:index }
Categorie_restau:
    path:     /categorieRestau
    defaults: { _controller: BonPlanBundle:Default:Categorierestau }
Acceuil_back:
    path:     /Acceuilback
    defaults: { _controller: BonPlanBundle:Default:AcceuilBack }
Ajouter:
    path:     /ajouter
    defaults: { _controller: BonPlanBundle:Default:Ajout }
Adminlog:
    path:     /Adminlog
    defaults: { _controller: BonPlanBundle:Default:adminlog }
detail_promo:
    path:     /detail_promo/{id}
    defaults: { _controller: BonPlanBundle:Promotion:detailPromo }
ConsulterP:
    path:     /ConsulterP
    defaults: { _controller: BonPlanBundle:Default:ConsulterP }
AjouterP:
    path:     /ajouterP/{id}
    defaults: { _controller: BonPlanBundle:Default:AjoutP }
Events:
    path:     /Events
    defaults: { _controller: BonPlanBundle:Default:Events }
liste_Promotion_Admin:
    path:     /Promotion
    defaults: { _controller: BonPlanBundle:Promotion:listPromotionAdmin }
Ajouter_Promotion:
    path:     /Ajout_Promotion
    defaults: { _controller: BonPlanBundle:Promotion:addPromo }
Modifier_Promotion:
    path:     /Modifier_Promotion/{id}
    defaults: { _controller: BonPlanBundle:Promotion:UpdatePromotion1 }
Supprimer_Promotion:
    path:     /Supprimer_Promotion
    defaults: { _controller: BonPlanBundle:Promotion:deletePromotion }
recherche_promotion:
    path:   /Recherche
    defaults: { _controller: BonPlanBundle:Promotion:Recherche }
bon_plan_homepage_back:
    path:     /admin
    defaults: { _controller: BonPlanBundle:Default:AcceuilBack }
liste_Promotion_Visiteur:
    path:     /PromotionVisiteur
    defaults: { _controller: BonPlanBundle:Promotion:listPromotionVisiteur }
recherche_promotion:
    path:   /recherche
    defaults: { _controller: BonPlanBundle:Promotion:Recherche}
recherche_promotionAdmin:
    path:   /rechercheAdmin
    defaults: { _controller: BonPlanBundle:Promotion:RechercheAdmin }
recherche_compte:
    path:   /rechercheP
    defaults: { _controller: BonPlanBundle:Admin:Recherche }
liste_Promotion_Prop:
    path:     /PromotionProp
    defaults: { _controller: BonPlanBundle:Promotion:Recherche_PromotionProp }
Profil_Plan:
    path:     /Profil_Plan/{id}
    defaults: { _controller: BonPlanBundle:Default:ConsulterP }

Validation_Compte:
    path:     /Validation
    defaults: { _controller: BonPlanBundle:Admin:ValiderCompte }
Validation:
    path:     /Validation/{id}
    defaults: { _controller: BonPlanBundle:Admin:Valider }
ajout_Categorie_admin:
    path:     /AjoutCategorie
    defaults: { _controller: BonPlanBundle:Categorie:CategAjout }
Categorie_admin:
    path:     /Suggestion
    defaults: { _controller: BonPlanBundle:Categorie:CategorieA }
ReservationVisiteur:
    path:     /ReservationVisiteur
    defaults: { _controller: BonPlanBundle:Reservation:afficherReservationVisiteur }
ReservationVisiteurSuppression:
    path:     /Supprimer/{id}
    defaults: { _controller: BonPlanBundle:Reservation:supprimerReservationVisiteur }
ReservationVisiteurUpdate:
    path:     /Update/{id}
    defaults: { _controller: BonPlanBundle:Reservation:updateReservationVisiteur }
ReservationProp:
    path:     /ReservationProp
    defaults: { _controller: BonPlanBundle:Reservation:afficherReservationProp }
ReservationPropUpdate:
    path:     /UpdateProp/{id}
    defaults: { _controller: BonPlanBundle:Reservation:updateReservationProp }
RecherchePlan:
    path:     /Recherche/{nomPlan}
    defaults: { _controller: BonPlanBundle:Default:RechercherPlan }
RechercheP:
    path:     /RechercheP
    defaults: { _controller: BonPlanBundle:Default:recherche }
ProfilProp:
    path:     /ProfilProp
    defaults: { _controller: BonPlanBundle:Default:ProfilProp }
EditProfilProp:
    path:     /EditProfilProp
    defaults: { _controller: BonPlanBundle:Default:EditProfilProp }
<<<<<<< HEAD

  #routing du module event
addEvent:
    path:     /Ajout_event
    defaults: { _controller: BonPlanBundle:Events:addEvent }
EventProp_consult:
    path:     /malisteEvent
    defaults: { _controller: BonPlanBundle:Events:afficherEventsProp }
PageEvent:
    path:     /pageEvent/{id}
    defaults: { _controller: BonPlanBundle:Events:afficherEvent }
=======
<<<<<<< HEAD
bon_plan_ReclamationPlan:
    path:     /ReclamerPlan/{id}
    defaults: { _controller: BonPlanBundle:Reclamation:ReclamerPlan }
=======
bon_plan_ReclamationP:
    path:     /ReclamerP
    defaults: { _controller: BonPlanBundle:Reclamation:ReclamerP }
bon_plan_ReclamationPlan:
    path:     /ReclamerPlan/{id}
    defaults: { _controller: BonPlanBundle:Reclamation:ReclamerPlan }
Profil_Plan:
    path:     /Profil_Plan/{id}
    defaults: { _controller: BonPlanBundle:Default:ConsulterPl }
>>>>>>> 2fc00991a238d4670f325c3fd33b98e2396eb468
Affiche_Rec:
    path:     /AfficheRec
    defaults: { _controller: BonPlanBundle:Reclamation:AfficheReclamation }
Update_Reclamation:
    path:     /UpdateRec/{idreclamation}
    defaults: { _controller: BonPlanBundle:Reclamation:UpdateReclamation}
Delete_Recalamation:
    path:     /DeleteRecAdmin/{idreclamation}
    defaults: { _controller: BonPlanBundle:Reclamation:DeleteReclamation }
bon_plan_abonner:
    path:     /bonPlan/abonner/{id}
    defaults: { _controller: BonPlanBundle:Abonner:abonner }
bon_plan_desabonner:
    path:     /bonPlan/desabonner/{idPlan}/{idUser}
<<<<<<< HEAD
    defaults: { _controller: BonPlanBundle:Abonner:desabonner }
=======
    defaults: { _controller: BonPlanBundle:Abonner:desabonner }
bon_plan_Stat:
      path:     /stat
      defaults: { _controller: BonPlanBundle:Stat:index}
>>>>>>> 2fc00991a238d4670f325c3fd33b98e2396eb468
>>>>>>> b820972144c8f32a32d404d0bb685d1561150cce
