services:
#    bon_plan.example:
#        class: BonPlanBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  redirect.after.login:
    class: BonPlanBundle\Redirection\AfterLoginRedirection
    arguments: ["@router"]
